### ISSUE TITLE
False negative query result after updating another indexed cell on same row

### ISSUE THREAD

**Issue by heskech** [tuplejump/stargate-core#33]
Stargate: 0.95 (and develop branch as of 10/21/2014)
Cassandra (DSE): 2.0.10

Description: Range query gives false negative after updating another cell (indexed or non-indexed) on the same row. The update should not have effected the filter results, yet the query is no longer able to find the row after the update. After dropping and recreating the stargate index, the filter works as expected, returning the row that fits the filter criteria.

Reproduction
--------------------------------

create keyspace reproduction with replication = {'class':'SimpleStrategy', 'replication_factor':1};
use reproduction;
create table times (
	id bigint,
	vt_from bigint,
	vt_to bigint,
	stargate text,
	PRIMARY KEY (id)
);

create custom index times_idx on times(stargate) using 'com.tuplejump.stargate.RowIndex' with options = 
{
	'sg_options':'{
		"fields":{
			"vt_from": {},
			"vt_to": {}
		}
	}'
};

insert into times (id, vt_from, vt_to) values (0, 0, 999999999);

select * from times where stargate = ' {
		filter: {type:"range", field:"vt_from", lower:0, upper:0, includeLower:true, includeUpper:true}	
}';

 id | stargate      | vt_from | vt_to
----+---------------+---------+-----------
  0 | {"score":1.0} |       0 | 999999999

(1 rows)

	
update times set vt_to = 201410210 where id = 0;

// This query gives the false negative. Should return same row as above.
select * from times where stargate = ' {
		filter: {type:"range", field:"vt_from", lower:0, upper:0, includeLower:true, includeUpper:true}	
}';

(0 rows)

**Comment by aaruna** [comment]
I do not see this issue in latest master and develop. This scenario is also covered in a Unit test. Closing this issue.
