### ISSUE TITLE
CQL collection with non-null value breaks filter

### ISSUE THREAD

**Issue by heskech** [tuplejump/stargate-core#34]
Version: Stargate 0.9.5 (and development branch as of 10/21/2014)
Cassandra (DSE): 2.0.10

Issue: Adding a CQL collection type (set specifically) results in false negative query result. The query will return the correct result if the value for the collection is either null or if I remove the column. The filter below should return one row. Instead, it returns zero, which is incorrect.

create keyspace reproduction with replication = {'class':'SimpleStrategy', 'replication_factor':1};
use reproduction;
create table bitemporal_index (
	id int,
	base text,
	parameters text,
	context text,
	vt bigint,
	tt set<bigint>,
	stargate text,
	PRIMARY KEY((id), vt)
) WITH CLUSTERING ORDER BY (vt DESC);

create custom index bitemporal_idx1 on bitemporal_index(stargate) using 'com.tuplejump.stargate.RowIndex' with options = {
	'sg_options':' {
		"fields":{
			"base":{},
			"parameters":{},
			"context":{},
			"vt":{}
		}
	}'
};

insert into bitemporal_index (id, base, parameters, context, vt, tt) values (1, 'TEST','','',0, {0});

// This query should return one row. Instead it returns zero rows.
select * from bitemporal_index where stargate = ' {
filter: {
	type: "boolean", must:[
		{type:"match", field:"base", value:"TEST"},
		{type:"range", field:"vt", lower:0, upper:201410210, includeLower:true, includeUpper:true}]
	}
}';

**Comment by aaruna** [comment]
I do not see this issue in develop and there are Unit tests for this scenario as well.
