### ISSUE TITLE
Lucene parser error when search for a word having double quote inside

### ISSUE THREAD

**Issue by rezarezash** [tuplejump/stargate-core#40]
I receive "Lucene parser error" when I execute below query even if I escape the double quote nothing change and same error comes\:

SELECT * FROM test  WHERE stargate ='{
    filter: {
        type: "lucene",
        field: "name",
        value: "lcd 15" "     ====> or   value: "lcd 15\" "
    }
}';

**Comment by trulite** [comment]
Can you please give a complete reproduction of the issue. We will need to check whether the column is analyzed or not(STRING vs TEXT).

**Comment by trulite** [comment]
Lucene cannot parse such queries. Please look into Lucene documentation for this kind of usage.
