### ISSUE TITLE
Issue in using list column

### ISSUE THREAD

**Issue by mehakmehta21** [tuplejump/stargate-core#51]
Hi,

I am using Cassandra 2.0.9 with Stargate-core.

I found a problem in tuplejump (stargate-core). When I am using it with a list type field in my table. The indexing stops working.
For e.g.
create table person (
    id int primary key,
    isActive boolean,
    age int,
    eyeColor varchar,
    name text,
    gender varchar,
    company varchar,
    email varchar,
    phone varchar,
    address text,
    points list<double>,
    stargate text
);

With indexing as: 
CREATE CUSTOM INDEX person_idx ON PERSON(stargate) USING some 
'com.tuplejump.stargate.RowIndex' WITH options =
{
        'sg_options':'{
                "fields":{
                		"eyeColor":{},
                        "age":{},
                        "phone":{}
                        }
        }'
};

If I insert data in the table along with points list. The following query won't give any results (0 rows):
SELECT * FROM RESULTS1 WHERE stargate ='{
    filter: {
        type: "range",
        field: "x",
        lower: 0
    }
}';

I tried removing points list<double> from the table and it works i.e. same query will return results as given in link (http://stargate-core.readthedocs.org/en/latest/quickstart.html). 

Kindly help me with this issue.

**Comment by trulite** [comment]
Can you please check out the develop branch and see if you are still facing this issue

**Comment by justinlinz** [comment]
trulite,

I was having a similar problem as described above and did as you suggest, build the develop branch and used those libraries.  Unfortunately I am still not seeing records with data in columns with a collection type being indexed/retrieved as expected.  Below is a set of three different scripts that display this behavior:

```cql
/*No data in collection col with map type, all is good*/
drop table if exists collectiontest;

CREATE TABLE collectiontest (
    userid VARCHAR,
    phones TEXT,
	address map<VARCHAR, VARCHAR>,
	stargate TEXT,
    PRIMARY KEY (userid)
);

CREATE CUSTOM INDEX collectionTest_search_idx ON collectiontest(stargate) USING
'com.tuplejump.stargate.RowIndex' WITH options =
{
        'sg_options':'{
                fields:{
                        phones:{}
                        }
        }'
};

INSERT INTO collectiontest(userid, phones) values ('user@notareal.dom.ain', 'aphone1');
INSERT INTO collectiontest(userid, phones) values ('guy@notareal.dom.ain', 'aphone2');


SELECT * FROM collectiontest WHERE stargate ='{
    filter: {
        type: "wildcard",
        field: "phones",
        value: "*phone*"
    }
}';

/*********************************************/
/*Data in collection col with MAP type for one row, its not in results, record without data in collection col is in results*/

drop table if exists collectiontest;

CREATE TABLE collectiontest (
    userid VARCHAR,
    phones TEXT,
	address map<VARCHAR, VARCHAR>,
	stargate TEXT,
    PRIMARY KEY (userid)
);

CREATE CUSTOM INDEX collectionTest_search_idx ON collectiontest(stargate) USING
'com.tuplejump.stargate.RowIndex' WITH options =
{
        'sg_options':'{
                fields:{
                        phones:{}
                        }
        }'
};

INSERT INTO collectiontest(userid, phones, address) values ('user@notareal.dom.ain', 'aphone1', {'key' : 'val'});
INSERT INTO collectiontest(userid, phones) values ('guy@notareal.dom.ain', 'aphone2');


SELECT * FROM collectiontest WHERE stargate ='{
    filter: {
        type: "wildcard",
        field: "phones",
        value: "*phone*"
    }
}';

/*********************************************/
/*Data in collection col with LIST type for one row, its not in results, record without data in collection col is in results*/

drop table if exists collectiontest;

CREATE TABLE collectiontest (
    userid VARCHAR,
    phones TEXT,
	address LIST<VARCHAR>,
	stargate TEXT,
    PRIMARY KEY (userid)
);

CREATE CUSTOM INDEX collectionTest_search_idx ON collectiontest(stargate) USING
'com.tuplejump.stargate.RowIndex' WITH options =
{
        'sg_options':'{
                fields:{
                        phones:{}
                        }
        }'
};

INSERT INTO collectiontest(userid, phones, address) values ('user@notareal.dom.ain', 'aphone1', ['val1', 'val2']);
INSERT INTO collectiontest(userid, phones) values ('guy@notareal.dom.ain', 'aphone2');


SELECT * FROM collectiontest WHERE stargate ='{
    filter: {
        type: "wildcard",
        field: "phones",
        value: "*phone*"
    }
}';
```

Thanks,
Justin

**Comment by trulite** [comment]
Thanks for the sample. I will test this and get back to you soon.

**Comment by aaruna** [comment]
I do not see this issue now in develop.
