### ISSUE TITLE
Howto rebuild index

### ISSUE THREAD

**Issue by rkubera** [tuplejump/stargate-core#53]
Hi.
I dropped index and created again (with different parameters) on large data set. After this operation i cannot search on stargate index (rpc timeout).
Is this possible to rebuild index?

Regards,
Radek.

**Comment by trulite** [comment]
Can you post a test case. The basic tests check for this and if this is not possible, it is a bug

**Comment by rkubera** [comment]
ok. It's no the problem with index but with timeout settings on client site.
