### ISSUE TITLE
while creating Row Index its shows error like this.

### ISSUE THREAD

**Issue by hopeuknow** [tuplejump/stargate-core#54]
while creating index its shows error like this.
ServerError: ErrorMessage code=0000 [Server error] message="java.lang.RuntimeEx
ception: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError
: org/apache/lucene/analysis/Analyzer"

**Comment by hopeuknow** [comment]
while creating index its shows error like this.
ServerError: ErrorMessage code=0000 [Server error] message="java.lang.RuntimeEx
ception: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError
: org/apache/lucene/analysis/Analyzer"

**Comment by trulite** [comment]
Have you copied the jars properly?
