### ISSUE TITLE
High CPU Utilization

### ISSUE THREAD

**Issue by justinlinz** [tuplejump/stargate-core#57]
We've noticed upon creating an index that uses stargate, it leads to high constant CPU utilization.  Even when the database is receiving no traffic, sitting idly, the cassandra process is sitting on at least 25% CPU utilization (and in some environments over a prolonged period of time we see ~100%) constantly.  If the stargate index is dropped, the processes CPU utilization drops back to 0.  
We tested with several scenarios, different types of indexes, both master and dev branches, and it occurs with each scenario that was tested.  To reproduce, start with a clean database, look at CPU usage, then run the following query (which is provided in the stargate dist as a sample):

CREATE TABLE PERSON (
    id int primary key,
    isActive boolean,
    age int,
    eyeColor varchar,
    name varchar,
    gender varchar,
    company varchar,
    email varchar,
    phone varchar,
    address text,
    stargate text
);

CREATE CUSTOM INDEX person_idx ON PERSON(stargate) USING
'com.tuplejump.stargate.RowIndex' WITH options =
{
        'sg_options':'{
                "fields":{
                        "age":{},
                        "eyeColor":{},
                        "name":{},
                        "gender":{},
                        "eyeColor":{},
                        "company":{},
                        "email":{},
                        "phone":{},
                        "address":{}
                }
        }'
};

In poking through the code, I think it may be related to the run method under the IndexEventSubscriber class, which seems to be looping continuously:
https://github.com/tuplejump/stargate-core/blob/master/src/main/java/com/tuplejump/stargate/IndexEventSubscriber.java#L59

Can you provide some insight into this please?

**Comment by trulite** [comment]
This is an unsatisfactory design decision at this moment when the system has a low number of cores. This seems to be performing okay on systems with high number of cores(since the Subscriber thread takes over one core mostly). How many cores are you testing with?

**Comment by justinlinz** [comment]
That makes sense as the two environments we tested were quad which showed ~25% util, and dual single cores which had ~100% of one cpu.  
Are there any plans on modifying that to prevent the unnecessary overhead?

**Comment by trulite** [comment]
This is now fixed
